site_name: Odyssey

# Repository
repo_name: auto_lab/odyssey
repo_url: https://gitlab.com/auto_lab/odyssey

extra_css:
  - stylesheets/extra.css
  - stylesheets/mkdocstrings.css


theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/gitlab

  custom_dir: docs/overrides

  font: 
    text: "Neo Sans Pro"
    code: "Gintronic"

  palette:
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: dtu-light
      toggle:
        icon: material/brightness-3
        name: Swich to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.tabs # Show tabs
    - navigation.tabs.sticky # Keep them on the screen
    - navigation.top # Back to top button when scrolling up
    - toc.follow
    - search.suggest
    - navigation.sections # Show sections in the sidebar
    #- navigation.footer
    #- announce.dismiss
    
    

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
  - Examples:
    - Single Objective Optimization: examples/single-objective-optimization.md
    - Multi Objective Optimization: examples/multi-objective-optimization.md
  - Reference:
    - Mission: api_reference/mission.md
    - Navigators: api_reference/navigators.md
  - About: about.md
  - Contact: contact.md

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options: 

          docstring_section_style: list
          
          # Headings
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_root_toc_entry: true
          show_root_heading: true
          show_root_full_path: false
          heading_level: 2
          show_source: false

          # Members
          inherited_members: false

          # Signatures
          separate_signature: true
          show_signature_annotations: true
          signature_crossrefs: true
          line_length: 1

markdown_extensions:
- toc: 
    toc_depth: 3

extra:
  generator: false  
